apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  namespace: tripinsights
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: registryvpc6526.azurecr.io/tripinsights/poi:latest
        imagePullPolicy: Always
        name: poi
        resources:
           limits:
             memory: 600Mi
             cpu: 2000m
           requests:
             memory: 300Mi
             cpu: 500m
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        env:
          - name: WEB_SERVER_BASE_URI
            value: 'http://0.0.0.0'
          - name: WEB_PORT
            value: '8080'
          - name: ASPNETCORE_ENVIRONMENT
            value: 'Production'
        envFrom:
        - secretRef:
            name: secret-sql-connection
---
apiVersion: v1
kind: Service
metadata:
  name: poi-svc
  namespace: tripinsights
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
    - protocol: TCP
      name: poi-http
      port: 80
      targetPort: 8080