apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-system-msi"
      containers:
      - name: trips
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        image: registryvpc6526.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        resources:
           limits:
             memory: 600Mi
             cpu: 2000m
           requests:
             memory: 300Mi
             cpu: 500m
 
---
apiVersion: v1
kind: Service
metadata:
  name: trips-svc
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: trips