apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registryvpc6526.azurecr.io/tripinsights/tripviewer:1.0
        ports:
        - containerPort: 80
        resources:
           limits:
             memory: 600Mi
             cpu: 2000m
           requests:
             memory: 300Mi
             cpu: 500m
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: http://userprofile-svc.api.svc.cluster.local/api/user
          - name: TRIPS_API_ENDPOINT
            value: http://trips-svc.api.svc.cluster.local
---

apiVersion: v1
kind: Service
metadata:
  name: tripviewer-svc
  namespace: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripviewer
