apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
  namespace: api
  labels:
    deploy: userprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-system-msi"
      containers:
      - image: registryvpc6526.azurecr.io/tripinsights/userprofile:1.0
        imagePullPolicy: Always
        name: userprofile
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        # resources:
        #    limits:
        #      memory: 600Mi
        #      cpu: 2000m
        #    requests:
        #      memory: 300Mi
        #      cpu: 500m
        ports:
          - containerPort: 80
            name: http
            protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-svc
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      name: userprofile-http
      port: 80
      targetPort: 80