kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-binding-api
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-admin
subjects:
- kind: Group
  namespace: api
  name: 37aadace-6ebc-451c-a7b7-6bf9f8c21120
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-dev-binding-web
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-viewer
subjects:
- kind: Group
  namespace: api
  name: 37aadace-6ebc-451c-a7b7-6bf9f8c21120