kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-binding-web
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-admin
subjects:
- kind: Group
  namespace: web
  name: 19da4358-fa62-4ca9-bac7-9280e36bdddb
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-dev-binding-api
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-viewer
subjects:
- kind: Group
  namespace: web
  name: 19da4358-fa62-4ca9-bac7-9280e36bdddb