apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: secret-store-oh-akv
    objects: |
      array:
        - |
          objectName: secret1        
          objectType: secret
          objectVersion: ""
    tenantId: 54b5e27e-ef82-4d67-a9ad-81bb9521d6f2